### ISSUE TITLE
Twitter card images are not working

### ISSUE THREAD

**Issue by andypiper** [developeravocados/avocados.dev#9]
I think the problem is the size of the images. From the Twitter card docs:

`Images for this Card support an aspect ratio of 2:1 with minimum dimensions of 300x157 or maximum of 4096x4096 pixels. Images must be less than 5MB in size.`

Looks like maybe the 1:1 ratio is not working well here.

Options:
- use a `summary` card type instead of `summary_large_image`; a square 1:1 image should work fine in that case
- find a function to cut a 2:1 aspect ratio image out (depending on the images used this might not be flattering, so might need to be done manually)

Happy to help here, if possible :-)

**Comment by AlexLakatos** [comment]
Thanks for spotting this! I've updated the Hugo page to not use the internal Twitter templates, so I could use summary cards. PRs are also welcomed if I've messed that up.

**Comment by andypiper** [comment]
Yep, the small images seem to be working - looks a bit better than before, and probably the easiest fix instead of trying to resize for the larger cards. Glad to assist 👍🏻
